### ISSUE TITLE
CoreCord unable to find MySQL driver

### ISSUE THREAD

**Issue by Firav** [M0diis/M0-CoreCord#3]
**Describe the bug**
Upon making a query to CoreCord, the plugin cannot connect to the database.

**To Reproduce**
1. Run CoreCord command from Discord.
2. Observe errors in console.

**Expected behavior**
Returned query of results from CoreProtect database.

**Screenshots**
![Screenshot](http://img.firav.us/images/2022/01/27/cmd_2022-01-27_13-08-42.png)

**Environment:**
 - OS: Debian 10
 - Server version: git-Paper-792 (1.16.5)
 - Java version 16
 - Plugin version 1.7.2

**Additional context**
This error occurs upon starting the plugin and on running any command functions.

**Comment by M0diis** [comment]
Hey.

Thanks for notifying about the issue.
I think I made a small typo in the SQL connector.

https://github.com/M0diis/M0-CoreCord/blob/0baa316bf633f3d83c0732e37195229471258e95/src/main/java/me/m0dii/corecord/CoSQL.java#L58-L61

Should be `Driver` and not `Drive`.
I'll try to resolve the issue as soon as possible.

**Comment by M0diis** [comment]
@Firav could you try the development build and let me know if the issue is fixed?
You can find the artifact [here](https://github.com/M0diis/M0-CoreCord/actions/runs/1758284915).

**Comment by Firav** [comment]
Seems as though this version works perfect! Thank you!

**Comment by M0diis** [comment]
No worries. Glad the issue is resolved.
Enjoy.
